source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'mysql2', '< 0.3'
gem 'rake', '0.8.7'
gem 'twitter'
gem 'oauth'
gem 'unicorn'
gem 'haml'
gem 'sass'
gem "compass", ">= 0.11.3"
gem 'rspec'
gem 'rspec-rails'
gem 'jquery-rails'
gem 'capistrano'
gem 'redis'